(delete '(company-dabbrev-code company-gtags company-etags company-keywords) company-backends)
(add-to-list 'company-backends '(company-dabbrev-code company-capf company-gtags company-etags company-keywords))
(define-key company-active-map (kbd "M-n") nil)
(define-key company-active-map (kbd "M-p") nil)
(define-key company-active-map (kbd "C-n") 'company-select-next)
(define-key company-active-map (kbd "C-p") 'company-select-previous)
(define-key company-active-map (kbd "C-h") nil)
(global-company-mode)
(setq company-minimum-prefix-length 2)
(setq company-selection-wrap-around t)
