(autoload 'yatex-mode "yatex" "Yet Another LaTeX mode" t)
(setq auto-mode-alist
      (append '(("\\.tex$" . yatex-mode)
                ("\\.ltx$" . yatex-mode)
                ("\\.cls$" . yatex-mode)
                ("\\.sty$" . yatex-mode)
                ("\\.clo$" . yatex-mode)
                ("\\.bbl$" . yatex-mode)) auto-mode-alist))
(setq YaTeX-kanji-code nil)
(setq tex-command "uplatex")
(setq dvi2-command "xdvi")
(setq bibtex-command "upbibtex")
(setq dviprint-command-format "dvipdfmx")
(add-hook 'yatex-mode-hook '(lambda () (auto-fill-mode -1)))
(add-hook 'yatex-mode-hook 'yas-global-mode)
