(autoload 'ghc-init "ghc" nil t)
(autoload 'ghc-debug "ghc" nil t)
(add-hook 'haskell-mode-hook (lambda ()
			       (ghc-init)
			       (bind-key "C-c n" (lambda () (interactive)(insert " -> ")) haskell-mode-map)
			       (bind-key "C-c m" (lambda () (interactive)(insert " => ")) haskell-mode-map)
			       (bind-key "C-c b" (lambda () (interactive)(insert " <- ")) haskell-mode-map)
			       ))
(add-to-list 'company-backends 'company-ghc)
