(autoload 'ghc-init "ghc" nil t)
(autoload 'ghc-debug "ghc" nil t)
(add-hook 'haskell-mode-hook (lambda ()
			       (ghc-init)
			       (bind-key "C-c C-k" (lambda () (interactive)(insert " -> ")))
			       (bind-key "C-c M-k" (lambda () (interactive)(insert " => ")))
			       (bind-key "C-c C-j" (lambda ()(interactive)(insert " <- ")))
			       ))
(add-to-list 'company-backends 'company-ghc)
